theme: minima
title: My Page
author: chiraag-kakar

description: > # this means to ignore newlines until "baseurl:"
  Hey Folks I am no more a beginner. 

# social links
twitter_username: 0212Chiraag # DO NOT include the @ character, or else the build will fail!
github_username:  chiraag-kakar # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
